name: PR Checks

on:
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    name: Build, Install and lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8 

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Build Next.js app
        run: pnpm build
      
      - name: Audit production dependencies for critical vulnerabilities
        run: pnpm audit --prod --audit-level=critical